# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppHero' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppHero

pod 'Alamofire', '~> 4.5'	#Gestion réseau
pod 'SwiftyJSON', '~> 3.1'	#Parsing JSON
pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'



end
